//
// ImportService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The set of available import service types. - 0 &#x3D; MyAnimeList - 1 &#x3D; Kitsu */
public enum ImportService: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
