//
// LibraryKind.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The set of available library kind types. - 0 &#x3D; anime - 1 &#x3D; manga - 2 &#x3D; game */
public enum LibraryKind: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
