//
// MediaType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The set of available media types. */
public enum MediaType: String, Codable, CaseIterable {
    case episodes = "episodes"
    case games = "games"
    case literatures = "literatures"
    case shows = "shows"
}
