//
// MediaCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The set of available media collections. */
public enum MediaCollection: String, Codable, CaseIterable {
    case _default = "default"
    case artwork = "artwork"
    case banner = "banner"
    case logo = "logo"
    case poster = "poster"
    case profile = "profile"
    case screenshot = "screenshot"
    case symbol = "symbol"
}
