//
// NSFWStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Whether the message contains NSFW material. - 0 &#x3D; no NSFW - 1 &#x3D; NSFW */
public enum NSFWStatus: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
