//
// ReplyStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Whether the message is a reply or not. If it&#39;s a reply then parent_id cannot be empty. - 0 &#x3D; not reply - 1 &#x3D; reply */
public enum ReplyStatus: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
