//
// ReShareStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Whether the message is a re-share. If it&#39;s a re-share then parent_id cannot be empty. - 0 &#x3D; not re-share - 1 &#x3D; re-share */
public enum ReShareStatus: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
