//
// SearchScope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The types used to perform the search. */
public enum SearchScope: String, Codable, CaseIterable {
    case kurozora = "kurozora"
    case library = "library"
}
