//
// SpoilerStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Whether the message contains spoiler material. - 0 &#x3D; no spoiler - 1 &#x3D; spoiler */
public enum SpoilerStatus: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
}
