//
// StoreProductType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The set of available store product types. - 0: Consumable - 1: Non-Consumable - 2: Non-Renewing Subscription - 3: Auto-Renewing Subscription */
public enum StoreProductType: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _3 = 3
}
